name: "Wait for Netlify Deploy"
description: "Wait for Netlify Deploy Preview to complete for a commit"
branding:
  icon: "clock"
  color: "blue"
inputs:
  site_name:
    description: "The Netlify site name to test against"
    required: true
  max_timeout:
    description: "The max time to run the action"
    required: false
outputs:
  url:
    description: "The fully qualified deploy preview URL"
runs:
  using: "node12"
  main: "index.js"
